import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNavigation } from "@/components/MainNavigation";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ClientProvider } from "@/contexts/ClientContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <ClientProvider>
            <div className="flex h-screen overflow-hidden">
              {/* Left Navigation - Fixed */}
              <aside className="flex-shrink-0 h-full overflow-hidden">
                <MainNavigation />
              </aside>
              
              {/* Main Content - Scrollable */}
              <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
                {children}
              </div>
            </div>
          </ClientProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
